# Generated by Django 6.0.3 on 2026-03-25 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (RU)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (EN)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('avatar_text', models.CharField(default='U', max_length=5, verbose_name='Текст аватара')),
                ('text_ru', models.TextField(verbose_name='Отзыв (RU)')),
                ('text_en', models.TextField(blank=True, verbose_name='Отзыв (EN)')),
                ('role_ru', models.CharField(max_length=100, verbose_name='Роль (RU)')),
                ('role_en', models.CharField(blank=True, max_length=100, verbose_name='Роль (EN)')),
                ('stars', models.IntegerField(default=5, verbose_name='Звёзды')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=10, verbose_name='Иконка (emoji)')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Заголовок (EN)')),
                ('slug', models.SlugField(default='', unique=True, verbose_name='Slug')),
                ('description_ru', models.TextField(verbose_name='Описание (RU)')),
                ('description_en', models.TextField(verbose_name='Описание (EN)')),
                ('full_description_ru', models.TextField(blank=True, verbose_name='Полное описание (RU)')),
                ('full_description_en', models.TextField(blank=True, verbose_name='Полное описание (EN)')),
                ('gradient', models.CharField(default='linear-gradient(135deg,#1a1a2e,#0f3460)', max_length=100, verbose_name='Градиент')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Khan', max_length=100, verbose_name='Имя')),
                ('title', models.CharField(default='Fullstack разработчик', max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(default='Laravel | Frontend | Python', max_length=300, verbose_name='Подзаголовок')),
                ('hero_text', models.TextField(default='Fullstack-разработчик. Избавляю от головной боли с кодом.', verbose_name='Текст на главной')),
                ('about_text', models.TextField(default='Профессионально избавляю вас от головной боли с кодом и недоделанными проектами.', verbose_name='Обо мне')),
                ('kwork_username', models.CharField(default='DevKhan', max_length=100, verbose_name='Kwork логин')),
                ('kwork_url', models.URLField(default='https://kwork.ru/user/devkhan', verbose_name='Kwork ссылка')),
                ('telegram_username', models.CharField(default='@asatkhanov', max_length=100, verbose_name='Telegram')),
                ('telegram_url', models.URLField(default='https://t.me/asatkhanov', verbose_name='Telegram ссылка')),
                ('telegram_bot_token', models.CharField(blank=True, help_text='Для отправки сообщений из формы', max_length=200, verbose_name='Telegram Bot Token')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Куда отправлять сообщения', max_length=50, verbose_name='Telegram Chat ID')),
                ('email', models.EmailField(default='hello@khan.dev', max_length=254, verbose_name='Email')),
                ('github_url', models.URLField(blank=True, default='https://github.com/', verbose_name='GitHub')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='Значение')),
                ('label_ru', models.CharField(max_length=100, verbose_name='Подпись (RU)')),
                ('label_en', models.CharField(max_length=100, verbose_name='Подпись (EN)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description_ru', models.TextField(verbose_name='Описание (RU)')),
                ('description_en', models.TextField(verbose_name='Описание (EN)')),
                ('full_description_ru', models.TextField(blank=True, verbose_name='Полное описание (RU)')),
                ('full_description_en', models.TextField(blank=True, verbose_name='Полное описание (EN)')),
                ('icon', models.CharField(default='🌐', max_length=10, verbose_name='Иконка (emoji)')),
                ('gradient', models.CharField(default='linear-gradient(135deg,#1a1a2e,#16213e)', max_length=100, verbose_name='Градиент фона')),
                ('image', models.ImageField(blank=True, upload_to='projects/', verbose_name='Главное изображение')),
                ('tags', models.CharField(default='Laravel, PHP, MySQL', max_length=500, verbose_name='Теги (через запятую)')),
                ('year', models.CharField(default='2025', max_length=10, verbose_name='Год')),
                ('status', models.CharField(default='Завершён', max_length=50, verbose_name='Статус')),
                ('client_name', models.CharField(default='Конфиденциально', max_length=100, verbose_name='Клиент')),
                ('demo_url', models.URLField(blank=True, verbose_name='Демо ссылка')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub ссылка')),
                ('is_featured', models.BooleanField(default=True, verbose_name='На главной')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Скриншот',
                'verbose_name_plural': 'Скриншоты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.CharField(max_length=300, verbose_name='Что входит (RU)')),
                ('text_en', models.CharField(blank=True, max_length=300, verbose_name='Что входит (EN)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='portfolio.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Что входит',
                'verbose_name_plural': 'Что входит',
                'ordering': ['order'],
            },
        ),
    ]
