# Generated by Django 6.0.3 on 2026-03-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите вместо emoji или как дополнение', upload_to='services/', verbose_name='Изображение'),
        ),
    ]
