# Generated by Django 6.0.3 on 2026-03-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен для заказов'),
        ),
    ]
