# Generated by Django 6.1 on 2026-08-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_sitesettings_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='resume',
            field=models.FileField(blank=True, help_text='PDF файл резюме для скачивания с главной страницы', null=True, upload_to='resume/', verbose_name='Резюме'),
        ),
    ]
