# Generated by Django 6.1 on 2026-08-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_sitesettings_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_en',
            field=models.TextField(blank=True, default='I professionally relieve you from coding headaches and unfinished projects.', verbose_name='Обо мне (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_text_en',
            field=models.TextField(blank=True, default='Fullstack developer. I solve your coding headaches.', verbose_name='Текст на главной (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='subtitle_en',
            field=models.CharField(blank=True, default='Laravel | Frontend | Python', max_length=300, verbose_name='Подзаголовок (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='title_en',
            field=models.CharField(blank=True, default='Fullstack Developer', max_length=200, verbose_name='Заголовок (EN)'),
        ),
    ]
