# Generated by Django 6.1 on 2026-08-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_sitesettings_about_text_en_sitesettings_hero_text_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='full_description_en',
        ),
        migrations.RemoveField(
            model_name='review',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='full_description_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='servicefeature',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_text_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_text_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='subtitle_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='label_en',
        ),
    ]
