# Generated by Django 6.1 on 2026-08-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_category_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.CharField(choices=[('globe', 'Веб-сайт / Глобальный (Globe)'), ('bot', 'Бот (Bot)'), ('database', 'База данных (Database)'), ('zap', 'Молния / Быстро (Zap)'), ('credit-card', 'Оплата (Credit Card)'), ('shopping-cart', 'Магазин (Shopping Cart)'), ('smartphone', 'Мобильный (Smartphone)'), ('server', 'Сервер (Server)'), ('code', 'Код (Code)'), ('layout-dashboard', 'Дашборд (Dashboard)'), ('settings', 'Настройки (Settings)'), ('shield', 'Безопасность (Shield)'), ('palette', 'Дизайн (Palette)'), ('pen-tool', 'Перо / Вектор (Pen Tool)'), ('cpu', 'Процессор (CPU)'), ('cloud', 'Облако (Cloud)'), ('briefcase', 'Портфель (Briefcase)'), ('check-circle', 'Галочка (Check Circle)'), ('message-square', 'Сообщение (Message)'), ('star', 'Звезда (Star)'), ('activity', 'Активность (Activity)')], default='globe', max_length=50, verbose_name='Иконка (Lucide)'),
        ),
    ]
