# Generated by Django 6.1 on 2026-08-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_project_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Адрес')),
                ('path', models.CharField(max_length=500, verbose_name='Страница')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referer', models.TextField(blank=True, verbose_name='Откуда перешел (Referer)')),
                ('is_mobile', models.BooleanField(default=False, verbose_name='Мобильный?')),
                ('is_tablet', models.BooleanField(default=False, verbose_name='Планшет?')),
                ('is_pc', models.BooleanField(default=False, verbose_name='ПК?')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Бот?')),
                ('browser_family', models.CharField(blank=True, max_length=100, verbose_name='Браузер')),
                ('os_family', models.CharField(blank=True, max_length=100, verbose_name='ОС')),
                ('device_family', models.CharField(blank=True, max_length=100, verbose_name='Устройство')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='Ключ сессии')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Аналитика посещений',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('globe', 'Веб-сайт / Глобальный (Globe)'), ('bot', 'Бот (Bot)'), ('database', 'База данных (Database)'), ('zap', 'Молния / Быстро (Zap)'), ('credit-card', 'Оплата (Credit Card)'), ('shopping-cart', 'Магазин (Shopping Cart)'), ('smartphone', 'Мобильный (Smartphone)'), ('server', 'Сервер (Server)'), ('code', 'Код (Code)'), ('layout-dashboard', 'Дашборд (Dashboard)'), ('settings', 'Настройки (Settings)'), ('shield', 'Безопасность (Shield)'), ('palette', 'Дизайн (Palette)'), ('pen-tool', 'Перо / Вектор (Pen Tool)'), ('cpu', 'Процессор (CPU)'), ('cloud', 'Облако (Cloud)'), ('briefcase', 'Портфель (Briefcase)'), ('check-circle', 'Галочка (Check Circle)'), ('message-square', 'Сообщение (Message)'), ('star', 'Звезда (Star)'), ('activity', 'Активность (Activity)')], default='globe', max_length=50, verbose_name='Иконка (Lucide)'),
        ),
    ]
