# Generated by Django 6.1 on 2026-08-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_pagevisit_alter_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='video',
            field=models.FileField(blank=True, help_text='Загрузите короткое видео. Если загружено, показывается вместо картинки.', null=True, upload_to='projects/gallery/videos/', verbose_name='Видео (MP4)'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/gallery/', verbose_name='Изображение'),
        ),
    ]
