# Generated by Django 6.1 on 2026-08-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_project_gradient_alter_service_gradient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='Организация')),
                ('image', models.ImageField(upload_to='certificates/', verbose_name='Фото/Скан')),
                ('issued_date', models.CharField(blank=True, max_length=50, verbose_name='Дата выдачи')),
                ('credential_id', models.CharField(blank=True, max_length=50, verbose_name='ID документа')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Длительность')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_full_text',
            field=models.TextField(default='Тут будет подробная история моего пути...', help_text='Поддерживает HTML-теги для форматирования', verbose_name='Развернутый текст обо мне'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portrait',
            field=models.ImageField(blank=True, help_text='Фото для страницы "Обо мне"', null=True, upload_to='about/', verbose_name='Портрет'),
        ),
    ]
