# Generated by Django 6.1 on 2026-08-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_certificate_sitesettings_about_full_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Компания / Проект')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('period', models.CharField(max_length=100, verbose_name='Период')),
                ('description', models.TextField(verbose_name='Описание (HTML)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
                'ordering': ['order'],
            },
        ),
    ]
