# Generated by Django 6.1 on 2026-08-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='gradient',
            field=models.CharField(choices=[('linear-gradient(135deg, #111111, #434343)', 'Тёмный (Dark Graphite)'), ('linear-gradient(135deg, #1a2980, #26d0ce)', 'Океан (Ocean Blue)'), ('linear-gradient(135deg, #0f2027, #203a43, #2c5364)', 'Космос (Deep Space)'), ('linear-gradient(135deg, #2c3e50, #3498db)', 'Небо (Sky Blue)'), ('linear-gradient(135deg, #ff4b1f, #ff9068)', 'Закат (Sunset Orange)'), ('linear-gradient(135deg, #4b6cb7, #182848)', 'Ночь (Cosmic Night)'), ('linear-gradient(135deg, #8E2DE2, #4A00E0)', 'Неон (Neon Purple)'), ('linear-gradient(135deg, #1D976C, #93F9B9)', 'Мята (Mint Green)'), ('linear-gradient(135deg, #F09819, #EDDE5D)', 'Золото (Golden Hour)'), ('linear-gradient(135deg, #3a1c71, #d76d77, #ffaf7b)', 'Сумерки (Twilight)')], default='linear-gradient(135deg, #111111, #434343)', max_length=100, verbose_name='Градиент фона'),
        ),
        migrations.AlterField(
            model_name='service',
            name='gradient',
            field=models.CharField(choices=[('linear-gradient(135deg, #111111, #434343)', 'Тёмный (Dark Graphite)'), ('linear-gradient(135deg, #1a2980, #26d0ce)', 'Океан (Ocean Blue)'), ('linear-gradient(135deg, #0f2027, #203a43, #2c5364)', 'Космос (Deep Space)'), ('linear-gradient(135deg, #2c3e50, #3498db)', 'Небо (Sky Blue)'), ('linear-gradient(135deg, #ff4b1f, #ff9068)', 'Закат (Sunset Orange)'), ('linear-gradient(135deg, #4b6cb7, #182848)', 'Ночь (Cosmic Night)'), ('linear-gradient(135deg, #8E2DE2, #4A00E0)', 'Неон (Neon Purple)'), ('linear-gradient(135deg, #1D976C, #93F9B9)', 'Мята (Mint Green)'), ('linear-gradient(135deg, #F09819, #EDDE5D)', 'Золото (Golden Hour)'), ('linear-gradient(135deg, #3a1c71, #d76d77, #ffaf7b)', 'Сумерки (Twilight)')], default='linear-gradient(135deg, #111111, #434343)', max_length=100, verbose_name='Градиент'),
        ),
    ]
