# Generated by Django 6.1 on 2026-08-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_project_gradient_alter_service_gradient'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Картинка 1200x630 (Telegram, VK)', null=True, upload_to='settings/', verbose_name='Превью для соцсетей (OG Image)'),
        ),
    ]
